export const EXAMPLE_CATEGORIES = ['Pizzas', 'Pastas', 'Entradas', 'Bebidas'] as const;

export type ExampleCategory = (typeof EXAMPLE_CATEGORIES)[number];

export interface ExampleProduct {
  id: string;
  name: string;
  description: string;
  price: number;
  category: ExampleCategory;
  available: boolean;}

export interface ExampleRestaurant {
  name: string;
  subtitle: string;
  hours: string;
  location: string;
}

export const EXAMPLE_RESTAURANT: ExampleRestaurant = {
  name: 'Bella Napoli',
  subtitle: 'Cocina italiana artesanal',
  hours: 'Abierto hoy · 12:00 - 23:30',
  location: 'Palermo, Buenos Aires',
  };

export const EXAMPLE_PRODUCTS: ExampleProduct[] = [
  {
    id: 'margherita',
    name: 'Margherita',
    description: 'Salsa de tomate, mozzarella fior di latte y albahaca fresca.',
    price: 12500,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'prosciutto',
    name: 'Prosciutto',
    description: 'Mozzarella, jamón crudo, rúcula y aceite de oliva.',
    price: 14900,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'diavola',
    name: 'Diavola',
    description: 'Salame picante, mozzarella, tomate y oliva.',
    price: 13800,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'quattro-formaggi',
    name: 'Quattro Formaggi',
    description: 'Mozzarella, gorgonzola, parmesano y provolone.',
    price: 15200,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'napolitana',
    name: 'Napolitana',
    description: 'Tomate, mozzarella, ajo, orégano y anchoas.',
    price: 13100,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'capricciosa',
    name: 'Capricciosa',
    description: 'Mozzarella, jamón cocido, champiñones y alcauciles.',
    price: 14500,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'funghi',
    name: 'Funghi',
    description: 'Mozzarella, mix de hongos salteados y aceite de trufa.',
    price: 14200,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'marinara',
    name: 'Marinara',
    description: 'Salsa de tomate, ajo, orégano y aceite de oliva.',
    price: 10800,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'calzone',
    name: 'Calzone Ripieno',
    description: 'Masa rellena de ricotta, espinaca, mozzarella y tomate.',
    price: 13900,
    category: 'Pizzas',
    available: false,  },
  {
    id: 'fugazzeta',
    name: 'Fugazzeta',
    description: 'Cebolla caramelizada, mozzarella y orégano.',
    price: 12800,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'burrata-pizza',
    name: 'Burrata e Pomodoro',
    description: 'Burrata fresca, tomates confitados y pesto de albahaca.',
    price: 16800,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'romana',
    name: 'Romana',
    description: 'Masa fina, mozzarella, anchoas, alcaparras y romero.',
    price: 13600,
    category: 'Pizzas',
    available: true,  },
  {
    id: 'lasagna',
    name: 'Lasagna della Casa',
    description: 'Pasta casera, carne braseada, tomate y bechamel.',
    price: 16500,
    category: 'Pastas',
    available: false,  },
  {
    id: 'carbonara',
    name: 'Spaghetti Carbonara',
    description: 'Guanciale crocante, yema, pecorino y pimienta negra.',
    price: 14800,
    category: 'Pastas',
    available: true,  },
  {
    id: 'alfredo',
    name: 'Fettuccine Alfredo',
    description: 'Manteca, crema, parmesano y nuez moscada.',
    price: 14200,
    category: 'Pastas',
    available: true,  },
  {
    id: 'arrabbiata',
    name: 'Penne Arrabbiata',
    description: 'Salsa de tomate picante, ajo y perejil fresco.',
    price: 11900,
    category: 'Pastas',
    available: true,  },
  {
    id: 'ravioli',
    name: 'Ravioli di Ricotta',
    description: 'Raviolis caseros rellenos de ricotta y espinaca.',
    price: 15400,
    category: 'Pastas',
    available: true,  },
  {
    id: 'gnocchi',
    name: 'Gnocchi al Pesto',
    description: 'Ñoquis de papa con pesto genovés y parmesano.',
    price: 13800,
    category: 'Pastas',
    available: true,  },
  {
    id: 'bolognesa',
    name: 'Tagliatelle Bolognesa',
    description: 'Pasta fresca con ragú de carne cocido a fuego lento.',
    price: 15100,
    category: 'Pastas',
    available: true,  },
  {
    id: 'canelones',
    name: 'Canelones de Ricotta',
    description: 'Canelones gratinados con salsa bechamel y tomate.',
    price: 15900,
    category: 'Pastas',
    available: true,  },
  {
    id: 'amatriciana',
    name: "Penne All'Amatriciana",
    description: 'Panceta, tomate San Marzano y pecorino romano.',
    price: 14600,
    category: 'Pastas',
    available: true,  },
  {
    id: 'lasagna-veg',
    name: 'Lasagna Vegetariana',
    description: 'Verduras asadas, ricotta, tomate y bechamel.',
    price: 15200,
    category: 'Pastas',
    available: true,  },
  {
    id: 'pappardelle',
    name: 'Pappardelle al Ragù',
    description: 'Cintas anchas con ragú de cordero y hierbas.',
    price: 17200,
    category: 'Pastas',
    available: true,  },
  {
    id: 'aglio-olio',
    name: 'Spaghetti Aglio e Olio',
    description: 'Ajo dorado, aceite de oliva, perejil y ají.',
    price: 10500,
    category: 'Pastas',
    available: true,  },
  {
    id: 'bruschetta',
    name: 'Bruschetta',
    description: 'Pan tostado, tomate cherry, albahaca y aceite de oliva.',
    price: 8700,
    category: 'Entradas',
    available: true,  },
  {
    id: 'carpaccio',
    name: 'Carpaccio di Manzo',
    description: 'Láminas de carne, rúcula, parmesano y limón.',
    price: 12400,
    category: 'Entradas',
    available: true,  },
  {
    id: 'burrata-entrada',
    name: 'Burrata con Tomates',
    description: 'Burrata cremosa, tomates heirloom y reducción balsámica.',
    price: 13200,
    category: 'Entradas',
    available: true,  },
  {
    id: 'caprese',
    name: 'Insalata Caprese',
    description: 'Mozzarella de búfala, tomate, albahaca y oliva.',
    price: 10900,
    category: 'Entradas',
    available: true,  },
  {
    id: 'focaccia',
    name: 'Focaccia al Rosmarino',
    description: 'Focaccia artesanal con sal marina y romero.',
    price: 7500,
    category: 'Entradas',
    available: true,  },
  {
    id: 'arancini',
    name: 'Arancini Siciliani',
    description: 'Croquetas de arroz rellenas de ragú y mozzarella.',
    price: 9800,
    category: 'Entradas',
    available: true,  },
  {
    id: 'caesar',
    name: 'Ensalada Caesar',
    description: 'Lechuga romana, croutons, parmesano y aderezo clásico.',
    price: 10200,
    category: 'Entradas',
    available: true,  },
  {
    id: 'provoleta',
    name: 'Provoleta Gratinada',
    description: 'Queso provolone fundido con orégano y aceite de oliva.',
    price: 9400,
    category: 'Entradas',
    available: true,  },
  {
    id: 'antipasto',
    name: 'Antipasto della Casa',
    description: 'Selección de embutidos, quesos, aceitunas y vegetales.',
    price: 14500,
    category: 'Entradas',
    available: true,  },
  {
    id: 'crema-zapallo',
    name: 'Crema de Zapallo',
    description: 'Crema suave de zapallo asado con croutons.',
    price: 8200,
    category: 'Entradas',
    available: false,  },
  {
    id: 'melanzane',
    name: 'Melanzane alla Parmigiana',
    description: 'Berenjenas gratinadas con salsa de tomate y mozzarella.',
    price: 11200,
    category: 'Entradas',
    available: true,  },
  {
    id: 'suppli',
    name: 'Supplì al Telefono',
    description: 'Arroz, ragú y mozzarella con centro filante.',
    price: 8900,
    category: 'Entradas',
    available: true,  },
  {
    id: 'limonata',
    name: 'Limonata',
    description: 'Limonada natural con menta y jengibre.',
    price: 5200,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'agua-mineral',
    name: 'Agua Mineral',
    description: 'Agua sin gas 500 ml.',
    price: 2800,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'agua-gas',
    name: 'Agua con Gas',
    description: 'Agua mineral con gas 500 ml.',
    price: 3000,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'coca-cola',
    name: 'Coca-Cola',
    description: 'Gaseosa 500 ml.',
    price: 3500,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'cerveza',
    name: 'Cerveza Artesanal',
    description: 'Rubia italiana 500 ml.',
    price: 5800,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'vino-tinto',
    name: 'Copa de Vino Tinto',
    description: 'Selección de la casa, crianza media.',
    price: 7200,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'vino-blanco',
    name: 'Copa de Vino Blanco',
    description: 'Pinot Grigio fresco y frutal.',
    price: 7200,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'espresso',
    name: 'Espresso',
    description: 'Café italiano corto y concentrado.',
    price: 3200,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso con leche espumada y cacao.',
    price: 4200,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'spritz',
    name: 'Aperol Spritz',
    description: 'Aperol, prosecco, soda y rodaja de naranja.',
    price: 8500,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'te-frio',
    name: 'Té Frío de Durazno',
    description: 'Té negro frío con durazno natural.',
    price: 4500,
    category: 'Bebidas',
    available: true,  },
  {
    id: 'prosecco',
    name: 'Copa de Prosecco',
    description: 'Espumante italiano seco y fresco.',
    price: 7800,
    category: 'Bebidas',
    available: false,  },
];

export function formatExamplePrice(price: number): string {
  return `$${price.toLocaleString('es-AR')}`;
}
